Fixed filter addition / removal bug
Refers to issue #14

Summary:
    Fixed bug where filters were added/removed to/from all RSS feeds
    simultaneously, by converting RSS feeds from an object to a basic
    dictionary
    Potentially fixed various unicode encoding bugs

modules/ajaxPage.py
    Removed filename encoding from `load_from_rss` (shifted this to
    modules/weblog.py)

modules/autohandler.py
    Various debugging changes (will be removed in next commit)

modules/remotes.py
    Renamed class `RSS` to `RSSFeed`
    Made class `RSSFeed` defunct, RSS feed information is now stored as
    a basic dictionary

modules/rpchandler.py
    Changed RSS download request to use AJAX function `load_from_rss`
    rather than `load_from_remote`

modules/rss.py
    Removed encoding of RSS element titles (shifted this to
    modules/weblog.py)

modules/weblog.py
    Added error handling for internal _process function
    TypeError: signifies that not enough arguments are passed for string
    formatting
    UnicodeDecodeError: signifies that there are non-ascii characters,
    responds by encoding with string_escape